# Generated by Django 3.2 on 2023-07-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=True, verbose_name='Стоимость услуги')),
                ('sort_position', models.SmallIntegerField(unique=True, verbose_name='Номер позиции')),
            ],
        ),
    ]
