# Generated by Django 3.2 on 2023-07-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprice',
            name='ot',
            field=models.BooleanField(default=True, verbose_name='Добавить предлог "от" к цене'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceprice',
            name='title',
            field=models.CharField(default=0, max_length=150, verbose_name='Название услуги'),
            preserve_default=False,
        ),
    ]
