# Generated by Django 3.2 on 2023-07-23 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20230723_1545'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceprice',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
    ]
