# Generated by Django 3.2 on 2023-07-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_auto_20230726_2056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bot',
            options={'verbose_name': 'Бот', 'verbose_name_plural': 'Боты'},
        ),
        migrations.AddField(
            model_name='bot',
            name='active',
            field=models.BooleanField(default=1, verbose_name='Является активным(должен быть единственным)'),
            preserve_default=False,
        ),
    ]
