# Generated by Django 3.2 on 2023-07-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_auto_20230726_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Является активным(должен быть единственным)'),
        ),
    ]
