# Generated by Django 3.2 on 2023-08-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_alter_bot_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Изображение')),
                ('description', models.CharField(default='Пример работ', max_length=50, verbose_name='Короткое описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='example_works/', verbose_name='Изображение')),
            ],
        ),
    ]
