# Generated by Django 3.2 on 2023-08-03 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'Пример работы', 'verbose_name_plural': 'Примеры работ'},
        ),
    ]
