# Generated by Django 3.2 on 2023-07-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telegram_manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telegram_id', models.CharField(max_length=9, verbose_name='id Telegram')),
                ('to_telegram', models.BooleanField(default=True, verbose_name='Отправка в Telegram')),
                ('to_email', models.BooleanField(default=True, verbose_name='Отправка на почту')),
            ],
        ),
    ]
