# Generated by Django 3.2 on 2023-07-21 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_telegram_manager'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegram_manager',
            options={'verbose_name': 'Менеджер', 'verbose_name_plural': 'Менеджеры'},
        ),
    ]
