# Generated by Django 3.2 on 2023-07-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_telegram_manager_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegram_manager',
            name='telegram_id',
            field=models.CharField(max_length=11, verbose_name='id Telegram'),
        ),
    ]
